### ISSUE TITLE
New fontra pak doesn't work on my intel macOS

### ISSUE THREAD

**Issue by RafalBuchner** [googlefonts/fontra-pak#107]
As in topic, I'm getting this fontra icon:
<img width="443" alt="image" src="https://github.com/googlefonts/fontra-pak/assets/18727963/2ad500e7-e1f7-4dc7-8f72-0c1210447ddb">

If I click on the icon, I'm getting popup message "You can’t open the application “Fontra Pak” because this application is not supported on this Mac.".

If I open the fontra-pak packagage with right-click, then "Show Package Content", double clicking exec file localized in  `Fontra Pak.app/Contents/MacOS/Fontra Pak`, I'm getting this output in terminal:
```
/Volumes/Fontra\ Pak/Fontra\ Pak.app/Contents/MacOS/Fontra\ Pak
zsh: bad CPU type in executable: /Volumes/Fontra Pak/Fontra Pak.app/Contents/MacOS/Fontra Pak
```

**Comment by justvanrossum** [comment]
Oh wow, GitHub actions quietly switched to Silicon for their macos-laters runners. Thanks for reporting, I'll try to get this fixed as soon as possible.

**Comment by justvanrossum** [comment]
I may have to drop support for macOS 10.15. Which macOS are you on?

**Comment by justvanrossum** [comment]
Ok, I managed to make the build produce Intel again. Please try to download again from https://fontra.xyz/.

(I'm trying to make a universal2 build, but so far I am failing.)

**Comment by justvanrossum** [comment]
You would do me a huge favor by checking if the macOS download from this build also works for you: https://github.com/googlefonts/fontra-pak/actions/runs/8854030735

**Comment by RafalBuchner** [comment]
doesn't work :( 
so now:
icon doesn't have this "stop" sign on it.
But when I try to run it by clicking on it, the icon appears on the macos' dock, and then dissappears. Nothing happens.
When I try to run exec file directly in terminal,  really weird thing happens:
```
➜  ~ Applications/Fontra\ Pak.app/Contents/MacOS/Fontra\ Pak
zsh: no such file or directory: Applications/Fontra Pak.app/Contents/MacOS/Fontra Pak
```

**Comment by justvanrossum** [comment]
1. Did you try the current one from fontra.xyz (should work again on Intel, I would be very susprised if it didn't)
2. Did you try the one from the GH actions run?

Can you also please tell me on what version of macOS you are?

**Comment by RafalBuchner** [comment]
current version from fontra.xyz works! thank you.
if it is still relevant: my macOS is Sonoma 14.4.1 (23E224)
