### ISSUE TITLE
screen glitches when pressing spacebar + dragging the canvas

### ISSUE THREAD

**Issue by martelahaie** [googlefonts/fontra-pak#33]
(working with external mouse and keyboard)

https://user-images.githubusercontent.com/103949453/235863589-04cf704e-6d26-4d8c-b5f3-ad8904df3b94.mov

**Comment by martelahaie** [comment]
(wrong channel)

**Comment by justvanrossum** [comment]
For reference: https://github.com/googlefonts/fontra/issues/441
