### ISSUE TITLE
Upload nightly builds elsewhere, so people can download them without logging into GH.

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra-pak#55]
The current build action could upload the two artifacts (Mac + Win builds) to a publically visible webserver, and we can then add static links to fontra.xyz. We wouldn't need to keep the history (old builds), we just need the latest build available at a static URL.

@fabiocaccamo, I would love your input on this.

**Comment by fabiocaccamo** [comment]
@justvanrossum we can upload the two artifacts directly to the webserver using SCP command.
Probably there is already a GitHub action for doing that, alternatively we can do it manually.

**Comment by fabiocaccamo** [comment]
I summarize the steps to follow to complete this activity:

- [ ] the .zip(s) artifacts should be uploaded via [SCP](https://github.com/appleboy/scp-action) + SSH credentials (limited user) to existing server (always using the same path/filename)
- [ ] nginx exposes the .zip files using a 3rd level subdomain, eg `https://download.fontra.xyz`
- [ ] the html links always point to the same .zip urls
- [ ] the .zip(s) timestamp can be retrieved performing two [HEAD requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) with JavaScript
